spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/shop?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/shop1?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver