
server:
  port: 8080
spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: work3
  #active: work2


