server:
  port: 8090

spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:
    application:
      name: order-service

mybatis:
  type-aliases-package: com.ylzt.geekbang.lesson08.work2.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

order-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule



